//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketDirectoryAPI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketDirectoryAPI.App_LocalResources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string completed_Text {
            get {
                return ResourceManager.GetString("completed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has failed to be sent to {email}.  Please try again.  If the problem continues ask your webmaster to check your SMTP and portal config..
        /// </summary>
        internal static string emailfail_Msg {
            get {
                return ResourceManager.GetString("emailfail.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Failure..
        /// </summary>
        internal static string emailfail_Text {
            get {
                return ResourceManager.GetString("emailfail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been sent to {email}.
        /// </summary>
        internal static string emailsent_Msg {
            get {
                return ResourceManager.GetString("emailsent.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent..
        /// </summary>
        internal static string emailsent_Text {
            get {
                return ResourceManager.GetString("emailsent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_Text {
            get {
                return ResourceManager.GetString("error.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string example_Text {
            get {
                return ResourceManager.GetString("example.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sub-categories in this category..
        /// </summary>
        internal static string nosubcategories_Text {
            get {
                return ResourceManager.GetString("nosubcategories.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs for pages on the client webiste can be added here, this allows for SEO links between API calls that happen.&lt;br/&gt;
        ///URLs can have tokens added for parameters that need to be added to the page link.  &lt;br/&gt;
        ///(User standard url format for compatibility across systems)
        ///
        ///.
        /// </summary>
        internal static string pagelinks_urlredirects_Text {
            get {
                return ResourceManager.GetString("pagelinks_urlredirects.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail URL is used to create SEO urls on the website.  It uses Article tokens to build a relative URL for the detail page..
        /// </summary>
        internal static string pageslinks_articledetail_Help {
            get {
                return ResourceManager.GetString("pageslinks_articledetail.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail URL.
        /// </summary>
        internal static string pageslinks_articledetail_Text {
            get {
                return ResourceManager.GetString("pageslinks_articledetail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List URL is used to create SEO urls on the website.  It uses article and category tokens to build a relative URL for the list page..
        /// </summary>
        internal static string pageslinks_articlelist_Help {
            get {
                return ResourceManager.GetString("pageslinks_articlelist.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article list URL.
        /// </summary>
        internal static string pageslinks_articlelist_Text {
            get {
                return ResourceManager.GetString("pageslinks_articlelist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging URL is used to create SEO urls on the website for paging the sarticle list..
        /// </summary>
        internal static string pageslinks_articlepaging_Help {
            get {
                return ResourceManager.GetString("pageslinks_articlepaging.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article  paging URL.
        /// </summary>
        internal static string pageslinks_articlepaging_Text {
            get {
                return ResourceManager.GetString("pageslinks_articlepaging.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of hours that need to have passed from the last scheduler run before the scheduler will run again.  This is also controlled in DNN, but is usually setup for every hour.  Usually we need to clear the database and do other operations only once a day.  Operations that need to run every hour are not effected by this setting..
        /// </summary>
        internal static string schedulerrunhours_Help {
            get {
                return ResourceManager.GetString("schedulerrunhours.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Run Hours.
        /// </summary>
        internal static string schedulerrunhours_Text {
            get {
                return ResourceManager.GetString("schedulerrunhours.Text", resourceCulture);
            }
        }
    }
}
